### ISSUE TITLE
Crash in German

### ISSUE THREAD

**Issue by balloonhead** [ApacheTech-VintageStory-Mods/ApacheTech.VintageMods.Knapster#3]
**Describe the Bug:**
After Installation of the Mod the game cannot load any map. It always says something went wrong. Installation has been done like told extract the mod in a seperate folder within Roaming VintagestoryData Mods. Cleared cache. Reinstalled the whole game version 1.7.10

**To Reproduce:**
Add the Mod Knapster

**Expected Behaviour:**
Savegame starts

**Additional Context**
the Game is set to german language. In the client-main Log it says failed to load de.json. Starting the game in english shows no error.

**Comment by ApacheTech** [comment]
Fixed.

Sorry about that. I had malformed JSON in the German translation file. Human error.
