### ISSUE TITLE
[BUG] Knapster seems not to work with 1.17.11 .net7

### ISSUE THREAD

**Issue by TeamRaZeR** [ApacheTech-VintageStory-Mods/ApacheTech.VintageMods.Knapster#5]
**Describe the Bug:**
The mod seems not to work with the .net7 version.

**To Reproduce:**
Use version 1.17.11 .net7 rc.1/rc.3.

**Expected Behaviour:**
The select tool doesn't work (the menu doesn't open) for knapping (that's what I've tested) and for clayforming, it doesn't show the auto-placement tab and also when changing amount of voxels, it just breaks 1 even if it is set to multiple voxels at a time. All the things were **enabled**.

**Additional Context**
Nothing.

**Comment by ApacheTech** [comment]
The mod is fully untested on the .NET7 version of the game, and v1.18 of the game. It is not designed to work with those versions of the game.

There will not be another compatibility update for this mod, until v1.18 is feature complete, and within it's Release Candidate stage.

At that point, the mod will have a full feature update cycle.
