### ISSUE TITLE
Smithing Crash

### ISSUE THREAD

**Issue by Ruyeex** [ApacheTech-VintageStory-Mods/ApacheTech.VintageMods.Knapster#6]
**Describe the Bug:**
The smithing system crashes my game.

**To Reproduce:**
-Hold the hammer on a anvil
**Expected Behaviour:**
-Instant Crash
Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.18.0 (Stable)
21/04/2023 21:56:49: Critical error occurred in the following mod: knapster@2.4.0
Loaded Mods: aculinaryartillery@1.0.12, buildinggadgets@0.4.0, chiseltools@1.8.4, cropsconfig@1.0.0, extendedcrafts@1.0.1, furniturelibrary@1.0.8, instruments@1.2.0, RangedWeapons@0.6.2, specializedbags-10Slot@0.4.2, ssppvv@1.0.4, game@1.18.0, carps@1.0.1, creativehotbar@0.2.0, expandedfoods@1.6.5, glidervar@1.1.0, hudclock@2.9.0, sailboat@1.0.0, notenoughfirewood@1.0.0, vanvar@3.1.1, creative@1.18.0, survival@1.18.0, knapster@2.4.0, morecandles@1.1.0, rifteye@0.1.1
Involved Harmony IDs: ApacheTech.VintageMods.Knapster, Version=2.4.0.0, Culture=neutral, PublicKeyToken=null
System.TypeInitializationException: O inicializador de tipo para 'Gantry.Core.LangEx' accionou uma excepção. ---> Newtonsoft.Json.JsonReaderException: Error reading JToken from JsonReader. Path '', line 0, position 0.
   em Newtonsoft.Json.Linq.JToken.ReadFrom(JsonReader reader, JsonLoadSettings settings)
   em Newtonsoft.Json.Linq.JToken.Parse(String json, JsonLoadSettings settings)
   em Vintagestory.API.Datastructures.JsonObject.FromJson(String jsonCode) em VintagestoryApi\Datastructures\JsonObject.cs:line 24
   em Gantry.Core.LangEx..cctor()
   --- Fim do rastreio da pilha de excepção interna ---
   em Gantry.Core.LangEx.FeatureString(String featureName, String path, Object[] args)
   em ApacheTech.VintageMods.Knapster.Features.EasySmithing.Patches.EasySmithingClientPatches.ClientPatch_ItemHammer_GetToolModes_Postfix(ItemHammer __instance, ItemSlot slot, IClientPlayer forPlayer, BlockSelection blockSel, SkillItem[]& __result, SkillItem[]& ___toolModes)
   em Vintagestory.GameContent.ItemHammer.GetToolModes_Patch1(ItemHammer this, ItemSlot slot, IClientPlayer forPlayer, BlockSelection blockSel)
   em Vintagestory.Client.NoObf.HudHotbar.UpdateCurrentToolMode(Int32 newSlotIndex) em VintagestoryLib\Client\Systems\Gui\Huds\HudHotbar.cs:line 139
   em Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) em VintagestoryLib\Common\EventManager.cs:line 85
   em Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) em VintagestoryLib\Client\ClientMain.cs:line 811
   em Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) em VintagestoryLib\Client\ClientMain.cs:line 710
   em Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) em VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 165
   em Vintagestory.Client.ScreenManager.Render(Single dt) em VintagestoryLib\Client\ScreenManager.cs:line 683
   em Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) em VintagestoryLib\Client\ScreenManager.cs:line 627
   em Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) em VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 126
   em System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   em OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) em C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   em OpenTK.GameWindow.DispatchRenderFrame() em C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   em OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) em C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   em Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   em Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) em VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
Newtonsoft.Json.JsonReaderException: Error reading JToken from JsonReader. Path '', line 0, position 0.
   em Newtonsoft.Json.Linq.JToken.ReadFrom(JsonReader reader, JsonLoadSettings settings)
   em Newtonsoft.Json.Linq.JToken.Parse(String json, JsonLoadSettings settings)
   em Vintagestory.API.Datastructures.JsonObject.FromJson(String jsonCode) em VintagestoryApi\Datastructures\JsonObject.cs:line 24
   em Gantry.Core.LangEx..cctor()

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 13/04/2023 00:35:44, Site = , Source = .NET Runtime, Message = Aplicação: Vintagestory.exe
Versão do Framework: v4.0.30319
Descrição: O processo foi terminado devido a uma excepção não processada.
Informações da Excepção: código de excepção c0020001, endereço da excepção 00007FFEF67BFDEC
Pilha:
 }
**Additional Context**
![image](https://user-images.githubusercontent.com/99507424/233733203-96b63cb4-90be-4968-b38b-246f96f5939f.png)

**Comment by ApacheTech** [comment]
Thanks for this. I'm trying to reproduce the error. I've changed my language to Portuguese, heated up some copper, and made a pair of Shears on an Iron Anvil, with a Steel Hammer. I used Auto-Complete, Heavy Strike, and Split. I couldn't get it to crash.

The crash happened when trying to display the "Auto Complete" label for the  hammer. I think I've narrowed it down, but I want to make sure.

A few questions, just so I can recreate it as closely as possible. You might not know all of them, but as much as you can give will be helpful. :)

Which exact language do you have your game set to?
Does this crash every time, for you, or only rarely?
What were you crafting? And what hammer were you holding?
What tool mode were you in?
What were your Knapster settings?
Was it on Single-Player, or Multiplayer?

**Comment by ApacheTech** [comment]
Never mind. I've found it.

The game added Portuguese (Portugal) as well as (Brazil), and I'm not falling back if it's not found. I'll add new translations, and update tonight. :)

**Comment by ApacheTech** [comment]
Fixed in v2.4.1:

Changelog

 - Added: Portuguese (Portugal) langauge support.
 - Added: Spanish (Latin America) language support.
 - Fixed: Languages now correctly fall back to English, when no language file is found.

**Comment by Ruyeex** [comment]
Which exact language do you have your game set to?
Portuguese
Does this crash every time, for you, or only rarely?
I think only me bcs i'm the only Portuguese Portugal
What were you crafting? And what hammer were you holding?
Anything but I was going for a musket, an steel hammer
What tool mode were you in?
None it crashes instantly
What were your Knapster settings?
Default
Was it on Single-Player, or Multiplayer?
Single player

**Comment by ApacheTech** [comment]
Thanks. :)

Up to 1.17, I had catered for all languages the game included. They added support for more languages in 1.18, and I hadn't added the translations for my mod. :) That's what caused the crash. It was trying to find a translation file that didn't exist. I've fixed this by adding translations for Portuguese (Portugal), and also making it fall back to English if no language files are found.

I use ChatGPT, and DeepL to translate the text in the game. If you see anything that needs to be updated, or changed, or doesn't make sense, please let me know, and I'll get it changed, ready for the next update.
