### ISSUE TITLE
[BUG] 1.18.6 .net7

### ISSUE THREAD

**Issue by SpeedRider** [ApacheTech-VintageStory-Mods/ApacheTech.VintageMods.Knapster#8]
**Describe the Bug:**
in 1.18.6 .net7 when pressing f it does not bring the added buttons up.

**To Reproduce:**
play in 1.18.6 .net7

**Expected Behaviour:**
being able to use the button so I can use auto use function 

**Additional Context**

**Comment by ApacheTech** [comment]
As has been stated multiple times, this version of the mod does not work in .NET7, and will not be released for .NET7, until such a time that ModDB can cater for both versions of the game. Currently, there is no way to release both .NET4, and .NET7 versions together. This will likely mean a new release for 1.19.

**Comment by McJty** [comment]
It's perfectly possible to release both NET4 and NET7 versions of a mod on ModDB. There are several mods that do that. For example: https://mods.vintagestory.at/volumetricshadingupdated

The trick is to just do multiple releases and indicate in that release for what version it is
